#!/bin/sh
count="$(checkupdates-with-aur | wc -l)"

class="ok"
if [ "$count" -gt 0 ]; then
    class="urgent"
elif [ "$count" -gt 10 ]; then
    class="warning"
fi

echo '{"text": "'$count'", "tooltip": "Updates pending: '$count'", "class": "'$class'"}'
